GET http://localhost:5000/rooms

###

POST http://localhost:5000/rooms
content-type: application/json

{
  "name": "Basique",
  "maxPersons": 5
}

###

GET http://localhost:5000/rooms/628df383829e3238916a0745

###

DELETE http://localhost:5000/rooms/629920230f19fa1351d9ea96

###

PATCH http://localhost:5000/rooms/62991d2c0f19fa1351d9ea69
content-type: application/json

{
  "_id": "62991d2c0f19fa1351d9ea69",
  "name": "chambre simple",
  "maxPersons": 1,
  "__v": 0,
  "promo": true
}
